### ISSUE TITLE
内容过旧

### ISSUE THREAD

**Issue by Shuisen** [dotnet/AspNetCore.Docs.zh-cn#245]
我选择的版本是ASP.NET Core 3.1的内容，然而这个页面介绍的仍是ASP.NET Core 2.x之前的内容，ASP.NET Core3.1之后路由中间件一般用新的中间件app.UseEndpoints(可兼容api等等)而不是之前的app.UseMvc，而且area必须指名路由[Area("XX")]和[Route("XX/[controller]/[action]")]

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 50249794-b4be-a6aa-d7b3-b3918eb282bf
* Version Independent ID: 39d98269-a7dc-017f-55cd-bd33df097368
* Content: [ASP.NET Core 中的区域](https://docs.microsoft.com/zh-cn/aspnet/core/mvc/controllers/areas?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/mvc/controllers/areas.md](https://github.com/dotnet/AspNetCore.Docs.zh-cn/blob/live/aspnetcore/mvc/controllers/areas.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @Shuisen
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by Rick-Anderson** [comment]
The version I choose is the content of ASP.NET Core 3.1. However, this page describes the content before ASP.NET Core 2.x. The routing middleware after ASP.NET Core 3.1 generally uses the new middleware app.UseEndpoints (Compatible with api, etc.) instead of the previous app.UseMvc, and area must be named routes [Area ("XX")] and [Route ("XX / [controller] / [action]")]

See https://github.com/dotnet/AspNetCore.Docs/pull/17094, which updated it to 3.1

See the [english version](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/areas?view=aspnetcore-3.1#feedback) which is updated.

@JasonCard  why isn't this version updated?

**Comment by JasonCard** [comment]
Source update was not being pick up by our loc platform, so I've escalated the issue and following up.
cc @CeciAc

**Comment by CeciAc** [comment]
Hi @JasonCard 
it looks like the content is updated
Please confirm if we can close the issue

**Comment by JasonCard** [comment]
@CeciAc Yes, this topics is now up-to-date for most language including Simplified Chinese, so closing this issue.
@Shuisen Thank you for your feedback and please let us know if you find any other issues.
