### ISSUE TITLE
 async controllers

### ISSUE THREAD

**Issue by JHeLiu** [dotnet/AspNetCore.Docs.zh-cn#252]
[在此处输入反馈]

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [教程：使用 ASP.NET Core 创建 Web API](https://docs.microsoft.com/zh-cn/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs.zh-cn/blob/live/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

On. Net core we're seeing more asynchronous controllers, and whether it's better to do that, or whether it's better to do that in a write case, or whether it's better to do that in a write case, or all of that, hopefully the documentation will give you a hint

**Comment by srvbpigh** [comment]
Hello, @JHeLiu
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [dotnet/AspNetCore.Docs #17302](https://github.com/dotnet/AspNetCore.Docs/issues/17302) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @JHeLiu, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/AspNetCore.Docs/issues/17302. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
