### ISSUE TITLE
@bind:format is not working

### ISSUE THREAD

**Issue by zxyao145** [dotnet/AspNetCore.Docs.zh-cn#255]
Hi, I'm try to implementation example @bind:format, here is the code
```
<input @bind-value="DateTime" @bind:format="yyyy-MM-dd" />
@code{
[Parameter]
public DateTime DateTime { get; set; } = DateTime.Now;
}
```

But I got error:
Microsoft.JSInterop.JSException: Failed to execute 'setAttribute' on 'Element': '@bind:format' is not a valid attribute name.

And I'm using blazorwasm:
Microsoft.AspNetCore.Components.WebAssembly.Templates::3.2.0-preview2.20160.5

So, is it only support Blazor Server? 
Thanks!

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 8b1b6ad8-13ba-0195-8829-ade3b1b0b9cb
* Version Independent ID: 6609ea68-a918-f3b9-8c9c-004a4436e350
* Content: [ASP.NET Core Blazor 数据绑定](https://docs.microsoft.com/zh-cn/aspnet/core/blazor/data-binding?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/blazor/data-binding.md](https://github.com/dotnet/AspNetCore.Docs.zh-cn/blob/live/aspnetcore/blazor/data-binding.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@zxyao145 ... To contact us directly in English using the **This page** feedback button+form, use the English page (segment "en-us" instead of "zh-cn" in the link). The localized doc page opens an issue for the localization team on this repo and then they end up having to close it and open a new issue for us on the main docs repo.

WRT to your question ... don't specify "value" on `@bind-value="DateTime"` ... try ...

```
<input @bind="DateTime" @bind:format="yyyy-MM-dd" />
```

**Comment by srvbpigh** [comment]
Hello, @zxyao145
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [dotnet/AspNetApiDocs #149](https://github.com/dotnet/AspNetApiDocs/issues/149) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @zxyao145, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/AspNetApiDocs/issues/149. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team

**Comment by guardrex** [comment]
It should be moved to the ASP.NET Core docs repo at ...

https://github.com/dotnet/AspNetCore.Docs/issues
