### ISSUE TITLE
please install the package Microsoft.VisualStudio.Web.CodeGeneration.Design

### ISSUE THREAD

**Issue by antonywusz** [dotnet/AspNetCore.Docs.zh-cn#257]
when entering into the step"Add Razor pages  using Entity Framework(CRUD)"
the ui shows scaffolding for a long time  and then shows the error including"please install the package Microsoft.VisualStudio.Web.CodeGeneration.Design"
and I try to install the Nuget with different version but the error still appears
<img width="950" alt="111" src="https://user-images.githubusercontent.com/34709085/78776390-5f73ca00-79ca-11ea-8f1f-cd2ad68429a9.png">

**Comment by srvbpigh** [comment]
Hello, @antonywusz
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [dotnet/AspNetCore.Docs #17677](https://github.com/dotnet/AspNetCore.Docs/issues/17677) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @antonywusz, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/AspNetCore.Docs/issues/17677. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
