### ISSUE TITLE
How can it return 401 code,not redirect to login page?

### ISSUE THREAD

**Issue by 717009629** [dotnet/AspNetCore.Docs.zh-cn#260]
How can it return 401 code,not redirect to login page?

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: d2229fc6-f8c8-952e-e567-b1d5a463055a
* Version Independent ID: b18a015b-914d-f014-f711-120d208904d9
* Content: [使用 cookie 而无需 ASP.NET Core 标识的身份验证](https://docs.microsoft.com/zh-cn/aspnet/core/security/authentication/cookie?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/security/authentication/cookie.md](https://github.com/dotnet/AspNetCore.Docs.zh-cn/blob/live/aspnetcore/security/authentication/cookie.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @717009629
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [dotnet/AspNetCore.Docs #17931](https://github.com/dotnet/AspNetCore.Docs/issues/17931) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @717009629, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/AspNetCore.Docs/issues/17931. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
