### ISSUE TITLE
connection error

### ISSUE THREAD

**Issue by 253513374** [dotnet/AspNetCore.Docs.zh-cn#274]
Many nodes have incorrect URL pointing。。It is too difficult to learn with such a deranged orientation.

**Comment by srvbpigh** [comment]
Hello, @253513374
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @253513374 
 
We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment?
 
Kind regards,
Microsoft DOCS International Team

**Comment by git-net** [comment]
many left nav item link error
eg
blazor >data binding(数据绑定) =》https://docs.microsoft.com/zh-cn/?view=aspnetcore-3.1

.........

**Comment by CeciAc** [comment]
Hello, @git-net 
 
We are following up on our previous comment. We need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment?

I cannot repro the error 

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @git-net 
 
Thanks once again for your comment.
Unfortunately, we are still missing information and we are unable to process your feedback. We are closing this GitHub issue at this time but we encourage you to submit more feedback in the future.

Kind regards,
Microsoft DOCS International Team
